version: '3.8'
services:
  backend:
    image: dycoren18/nutrition-backend:latest
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - SECRET_KEY=${SECRET_KEY}
      - GOOGLE_API_KEY=${GOOGLE_API_KEY}
      - SMTP_EMAIL=${SMTP_EMAIL}
      - SMTP_PASSWORD=${SMTP_PASSWORD}
      - FRONTEND_URL=${FRONTEND_URL}

  frontend:
    image: dycoren18/nutrition-frontend:latest
    ports:
      - "80:80"
    environment:
      - REACT_APP_API_URL=https://dailybite-backend.runmydocker-app.com
    depends_on:
      - backend